const PDFDocument = require('pdfkit');
const fs = require('fs');

class PDFReportGenerator {
  generateReport(reportData) {
    const doc = new PDFDocument({ margin: 50 });
    let buffers = [];
    
    doc.on('data', buffers.push.bind(buffers));
    
    return new Promise((resolve) => {
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      // Header
      doc.fontSize(24).fillColor('#1e40af').text('CyberGuardX Security Report', 50, 50);
      doc.fontSize(16).fillColor('#1f2937').text(`Target: ${reportData.targetUrl}`, 50, 80);
      
      // Report Info
      doc.rect(50, 110, 500, 60).stroke('#1e40af');
      doc.fontSize(12).fillColor('#1f2937')
         .text(`Report ID: ${reportData.reportId}`, 60, 125)
         .text(`Date: ${new Date().toLocaleDateString()}`, 60, 145)
         .text(`Vulnerabilities: ${reportData.vulnerabilities?.length || 0}`, 300, 125)
         .text(`Risk Level: ${reportData.summary?.riskLevel || 'Medium'}`, 300, 145);
      
      doc.moveDown(3);
      
      // Executive Summary
      doc.fontSize(18).fillColor('#1e40af').text('Executive Summary', 50, 200);
      doc.fontSize(12).fillColor('#1f2937')
         .text(`Total vulnerabilities found: ${reportData.vulnerabilities?.length || 0}`, 50, 230);
      
      if (reportData.summary?.severityBreakdown) {
        const breakdown = reportData.summary.severityBreakdown;
        doc.text(`Critical: ${breakdown.critical || 0} | High: ${breakdown.high || 0} | Medium: ${breakdown.medium || 0} | Low: ${breakdown.low || 0}`, 50, 250);
      }
      
      // Vulnerabilities
      if (reportData.vulnerabilities?.length > 0) {
        doc.addPage();
        doc.fontSize(18).fillColor('#1e40af').text('Vulnerability Details', 50, 50);
        
        let yPos = 80;
        reportData.vulnerabilities.forEach((vuln, index) => {
          if (yPos > 700) {
            doc.addPage();
            yPos = 50;
          }
          
          doc.fontSize(14).fillColor('#ef4444').text(`${index + 1}. ${vuln.type || vuln.title}`, 50, yPos);
          doc.fontSize(11).fillColor('#1f2937')
             .text(`Severity: ${vuln.severity}`, 50, yPos + 20)
             .text(`Location: ${vuln.location || 'N/A'}`, 50, yPos + 35)
             .text(`Description: ${vuln.description || 'No description'}`, 50, yPos + 50);
          
          yPos += 100;
        });
      }
      
      // Footer
      doc.fontSize(10).fillColor('#6b7280')
         .text(`Generated by CyberGuardX on ${new Date().toLocaleString()}`, 50, 750);
      
      doc.end();
    });
  }
}

module.exports = PDFReportGenerator;